# permission-ы в плагине
# check.check - игрок с этим правом может вызывать других игроков на проверку (/check)
# check.moderator - игрока с этим правом нельзя вызвать на проверку
# check.notify - получать оповещения о проверках

# Сообщения плагина
messages:
  chat-prefix: '' # Префикс всех сообщений в чате (можно убрать, заменив значение на ~)
  check-notification:
    start: |-
      §b 
      §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
      §b 
      §6§l▌ §fАдминистратор §f§l➲ §6§l{moderator} §fуспешно вызвал вас на проверку.
      §6§l▌ §fСвяжисть с администратором, чтобы пройти проверку.
      §6§l▌ §fДля связи с администратором, выполните команду §f§l➲ §6§l/m {moderator}
      §6§l▌ §d
      §6§l▌ §fЕсли вы покинете игру, вы будете автоматически заблокированы навсегда по
      §6§l▌ §6§lIP §fпо правилу §6§l3.1§f§l.
      §6§l▌ §fЕсли вы хотите признаться в использование читов, выполните команду §f§l➲
      §6§l▌ §6§l/iamcheater
      §6§l▌ §fПосле выполнения команды §f§l➲ §6§l/iamcheater §fвы будете автоматически
      §6§l▌ §fзаблокированы навсегда по §6§lIP §fпо правилу §6§l3.1§f§l.
      §b 
      §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
      §b
    repeat:
      title: '§c§l⚠ ПРОВЕРКА НА ЧИТЫ ⚠'
      actionbar: '§c§l⚠ §fАдминистратор §f§l➲ §6§l{moderator} §fуспешно вызвал вас на проверку §c§l⚠'
    period: 1.5 # Задержка между показами. Дробные секунды (!!! ДРОБНАЯ ЧАСТЬ - НЕ МИЛЛИСЕКУНДЫ !!!)
  not-permitted: '§6§lПРОВЕРКА: §cУ вас нет разрешения на использование данной команды.'
  player-not-found: '§6§lПРОВЕРКА: §fДанного игрока нет на сервере.'
  check-command-help: '§6§lПРОВЕРКА: §fПравильное использование команды §f§l➲ §6§l/check §f§l<§6§lНикнейм игрока§f§l>' # Если вводишь "/check" без аргументов
  no-such-moderator-action: '§6§lПРОВЕРКА: §fПравильное использование команды §f§l➲ §6§l/check §f§l<§6§lНикнейм игрока§f§l> §6§lconfirm§f§l/§6§lcancel§f§l/§6§lleave§f§l/§6§ldeleted§f§l/§6§lignore' # Если вместо confirm/cancel/leave/deleted/ignore модератор ввёл что-то другое
  # ввёл "/check <кто-то, кого не вызвали на проверку> cancel" (или что-то другое)
  player-is-not-being-checked: '§6§lПРОВЕРКА: §fВы не вызывали игрока §f§l➲ §6§l{player} §fна проверку, чтобы выполнять данную команду на игрока §f§l➲ §6§l{player}&f&l.'
  cannot-check-moderator: '§6§lПРОВЕРКА: §fВы не можете вызвать на проверку игрока §f§l➲ §6§l{moderator}&f&l.' # Есть право echeck.moderator
  player-already-being-checked: '§6§lПРОВЕРКА: §fИгрок §f§l➲ §6§l{player} §fуже проверяется администратором §f§l➲ §6§l{moderator}&f&l.'
  you-already-checking-this-player: '§6§lПРОВЕРКА: §fВы уже проверяете игрока §f§l➲ §6§l{player}&f&l.'
  you-cannot-check-yourself: '§6§lПРОВЕРКА: §fВы не можете вызвать на проверку самого себя.'
  checking-player: '§6§lПРОВЕРКА: §fВы успешно вызвали игрока §f§l➲ §6§l{player} §fна проверку.'
  # Это сообщение получает игрок, которого проверяли, если он успешно прошёл проверку
  you-passed-check: '§6§lПРОВЕРКА: §fВы успешно прошли проверку. §fПроверку проводил администратор §f§l➲ §6§l{moderator}&f&l.'
  # Эти два сообщения получает игрок, проводивший проверку и игроки, которые имеют право echeck.notify
  player-passed-check: '§6§lПРОВЕРКА: §fИгрок §f§l➲ §6§l{player} §fуспешно прошел проверку. §fПроверку проводил администратор §f§l➲ §6§l{moderator}&f&l.' # Игрок, которого проверяли, это сообщение не видит
  player-failed-check: '§6§lПРОВЕРКА: §fИгрок §f§l➲ §6§l{player} §fне прошел проверку и был заблокирован. §fПроверку проводил администратор §f§l➲ §6§l{moderator}&f&l.'

# Ограничения для игрока во время проверки
restrictions:
  movement: no # Отключить передвижение
  chat: no # Отключить чат
  commands: # Отключить возможность исполнять команды
    enable: yes
    whitelist: # Белый список команд, которые игрок исполнять, несмотря на ограничение (команда iamcheater уже в белом списке)
      - msg
      - m
      - pm
      - r
      - tell
  block-placing: yes # Отключить возможность ставить блоки
  block-breaking: yes # Отключить возможность ломать блоки
  dropping-items: yes # Отключить возможность выбрасывать предметы
  inventory-interaction: yes # Отключить возможность открывать любой инвентарь
  attacking: yes # Отключить возможность атаковать

player-invulnerable-while-checking: yes # Сделать игрока неуязвимым во время проверки

# Дополнительные фичи плагина
features:
  iamcheater-cmd: yes # Команда iamcheater

# Команды в плагине
commands:
  executor: moderator # Исполнитель команд. console - команды исполняются от консоли. moderator - команды исполняются от модератора
  punish-quit: 'banip {player} Покинул игру во время проверки 3.1' # Игрок вышел сам
  punish-cheats: 'banip {player} Найдены читы на проверке 3.1' # Модератор подтвердил читы
  punish-dodged: 'banip {player} Уход от проверки 3.1' # Сбежал с проверки
  punish-cheat-files-found: 'tempban {player} 15d Найдены удаленные читы 3.1' # Найдены какие-либо файлы читов (или найдены удалённые читы)
  punish-ignored: 'banip {player} Игнорирование проверки 3.1' # Проигнорировал
  punish-fair: 'banip {player} Самопризнание 3.1' # Признался в читах