name: EpicSub
version: '${version}'

main: hgds.epicgrief.EpicSub
api-version: '26.1.2'
load: STARTUP

authors: [ hgds_2 ]
softdepend: [ LuckPerms, TAB, PlaceholderAPI ]

commands:
  sub:
    description: EpicSub subscription command
    usage: /sub
    aliases: [ epicsub, epicplus, plus ]

permissions:
  epicsub.admin:
    default: op
  epicsub.give:
    default: op
  epicsub.take:
    default: op
  epicsub.check.others:
    default: op
  epicsub.reload:
    default: op
