chains:
  mode: 'reset-next-week'
    rewards:
      1:
        command: 'reward-1'
        actions:
          - 'ecase give donatefree {player} 1'
        direct-message: '&6&lХАЛЯВА: &fВы успешно получили &f&l➲ &6&lНАГРАДУ #1'
        broadcast: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fИгрок &6&l{player} &fуспешно получил &4&l⇩
          &8 &8║ &fБесплатный кейс с донатом &f&l➲ &6&l1 штуку
          &8 &8╚ &fЕсли хотите также, выполните команду &f&l➲ &6&l&n/ＦＲＥＥ&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
        not-ready: '&6&lХАЛЯВА: &fВам необходимо отыграть еще &f&l➲ &6&l{remains}&f&l, &fдля получения награды.'
        already-given: '&6&lХАЛЯВА: &fВы уже получали данную награду.'
        delay: 20m
        notification: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fВы можете получить &4&l⇩
          &8 &8║ &fБесплатный кейс с донатом &f&l➲ &6&l1 штуку
          &8 &8╚ &fДля получения награды за наигранное время, выполните команду &f&l➲ &6&l&n/reward-1&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
      2:
        command: 'reward-2'
        actions:
          - 'ecase give donatefree {player} 2'
        direct-message: '&6&lХАЛЯВА: &fВы успешно получили &f&l➲ &6&lНАГРАДУ #2'
        broadcast: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fИгрок &6&l{player} &fуспешно получил &4&l⇩
          &8 &8║ &fБесплатный кейс с донатом &f&l➲ &6&l2 штуки
          &8 &8╚ &fЕсли хотите также, выполните команду &f&l➲ &6&l&n/ＦＲＥＥ&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
        not-ready: '&6&lХАЛЯВА: &fВам необходимо отыграть еще &f&l➲ &6&l{remains}'
        already-given: '&6&lХАЛЯВА: &fВы уже получали данную награду.'
        delay: 40m
        notification: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fВы можете получить &4&l⇩
          &8 &8║ &fБесплатный кейс с донатом &f&l➲ &6&l2 штуки
          &8 &8╚ &fДля получения награды за наигранное время, выполните команду &f&l➲ &6&l&n/reward-2&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
      3:
        command: 'reward-3'
        actions:
          - 'ecase give money {player} 1'
        direct-message: '&6&lХАЛЯВА: &fВы успешно получили &f&l➲ &6&lНАГРАДУ #3'
        broadcast: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fИгрок &6&l{player} &fуспешно получил &4&l⇩
          &8 &8║ &fПлатный кейс с франками &f&l➲ &6&l1 штуку
          &8 &8╚ &fЕсли хотите также, выполните команду &f&l➲ &6&l&n/ＦＲＥＥ&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
        not-ready: '&6&lХАЛЯВА: &fВам необходимо отыграть еще &f&l➲ &6&l{remains}'
        already-given: '&6&lХАЛЯВА: &fВы уже получали данную награду.'
        delay: 60m
        notification: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fВы можете получить &4&l⇩
          &8 &8║ &fПлатный кейс с франками &f&l➲ &6&l1 штуку
          &8 &8╚ &fДля получения награды за наигранное время, выполните команду &f&l➲ &6&l&n/reward-3&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
      4:
        command: 'reward-4'
        actions:
          - 'ecase give money {player} 2'
        direct-message: '&6&lХАЛЯВА: &fВы успешно получили &f&l➲ &6&lНАГРАДУ #4'
        broadcast: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fИгрок &6&l{player} &fуспешно получил &4&l⇩
          &8 &8║ &fПлатный кейс с франками &f&l➲ &6&l2 штуки
          &8 &8╚ &fЕсли хотите также, выполните команду &f&l➲ &6&l&n/ＦＲＥＥ&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
        not-ready: '&6&lХАЛЯВА: &fВам необходимо отыграть еще &f&l➲ &6&l{remains}'
        already-given: '&6&lХАЛЯВА: &fВы уже получали данную награду.'
        delay: 100m
        notification: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fВы можете получить &4&l⇩
          &8 &8║ &fПлатный кейс с франками &f&l➲ &6&l2 штуки
          &8 &8╚ &fДля получения награды за наигранное время, выполните команду &f&l➲ &6&l&n/reward-4&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
      5:
        command: 'reward-5'
        actions:
          - 'ecase give donateshop {player} 1'
        direct-message: '&6&lХАЛЯВА: &fВы успешно получили &f&l➲ &6&lНАГРАДУ #5'
        broadcast: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fИгрок &6&l{player} &fуспешно получил &4&l⇩
          &8 &8║ &fПлатный кейс с донатом &f&l➲ &6&l1 штуку
          &8 &8╚ &fЕсли хотите также, выполните команду &f&l➲ &6&l&n/ＦＲＥＥ&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
        not-ready: '&6&lХАЛЯВА: &fВам необходимо отыграть еще &f&l➲ &6&l{remains}'
        already-given: '&6&lХАЛЯВА: &fВы уже получали данную награду.'
        delay: 120m
        notification: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fВы можете получить &4&l⇩
          &8 &8║ &fПлатный кейс с донатом &f&l➲ &6&l1 штуку
          &8 &8╚ &fДля получения награды за наигранное время, выполните команду &f&l➲ &6&l&n/reward-5&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
      6:
        command: 'reward-6'
        actions:
          - 'ecase give donateshop {player} 2'
        direct-message: '&6&lХАЛЯВА: &fВы успешно получили &f&l➲ &6&lНАГРАДУ #6'
        broadcast: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fИгрок &6&l{player} &fуспешно получил &4&l⇩
          &8 &8║ &fПлатный кейс с донатом &f&l➲ &6&l2 штуки
          &8 &8╚ &fЕсли хотите также, выполните команду &f&l➲ &6&l&n/ＦＲＥＥ&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
        not-ready: '&6&lХАЛЯВА: &fВам необходимо отыграть еще &f&l➲ &6&l{remains}'
        already-given: '&6&lХАЛЯВА: &fВы уже получали данную награду.'
        delay: 180m
        notification: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fВы можете получить &4&l⇩
          &8 &8║ &fПлатный кейс с донатом &f&l➲ &6&l2 штуки
          &8 &8╚ &fДля получения награды за наигранное время, выполните команду &f&l➲ &6&l&n/reward-6&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
      7:
        command: 'reward-7'
        actions:
          - 'coins add {player} 300'
          - 'eco give {player} 25000'
          - 'ecase give suffix_anime {player} 1'
        direct-message: '&6&lХАЛЯВА: &fВы успешно получили &f&l➲ &6&lНАГРАДУ #7'
        broadcast: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fИгрок &6&l{player} &fуспешно получил &4&l⇩
          &8 &8║ &fФранки &f&l➲ &6&l300
          &8 &8║ &fМонеты &f&l➲ &6&l25000
          &8 &8║ &fКейс с аниме титулами &f&l➲ &6&l1 штука
          &8 &8╚ &fЕсли хотите также, выполните команду &f&l➲ &6&l&n/ＦＲＥＥ&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
        not-ready: '&6&lХАЛЯВА: &fВам необходимо отыграть еще &f&l➲ &6&l{remains}'
        already-given: '&6&lХАЛЯВА: &fВы уже получали данную награду.'
        delay: 180m
        notification: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fВы можете получить &4&l⇩
          &8 &8║ &fФранки &f&l➲ &6&l300
          &8 &8║ &fМонеты &f&l➲ &6&l25000
          &8 &8║ &fКейс с аниме титулами &f&l➲ &6&l1 штука
          &8 &8╚ &fДля получения награды за наигранное время, выполните команду &f&l➲ &6&l&n/reward-7&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
      8:
        command: 'reward-8'
        actions:
          - 'coins add {player} 600'
          - 'eco give {player} 50000'
          - 'ecase give suffix_privat {player} 1'
        direct-message: '&6&lХАЛЯВА: &fВы успешно получили &f&l➲ &6&lНАГРАДУ #8'
        broadcast: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fИгрок &6&l{player} &fуспешно получил &4&l⇩
          &8 &8║ &fФранки &f&l➲ &6&l600
          &8 &8║ &fМонеты &f&l➲ &6&l50000
          &8 &8║ &fКейс с приватными титулами &f&l➲ &6&l1 штука
          &8 &8╚ &fЕсли хотите также, выполните команду &f&l➲ &6&l&n/ＦＲＥＥ&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
        not-ready: '&6&lХАЛЯВА: &fВам необходимо отыграть еще &f&l➲ &6&l{remains}'
        already-given: '&6&lХАЛЯВА: &fВы уже получали данную награду.'
        delay: 220m
        notification: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fВы можете получить &4&l⇩
          &8 &8║ &fФранки &f&l➲ &6&l600
          &8 &8║ &fМонеты &f&l➲ &6&l50000
          &8 &8║ &fКейс с приватными титулами &f&l➲ &6&l1 штука
          &8 &8╚ &fДля получения награды за наигранное время, выполните команду &f&l➲ &6&l&n/reward-8&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
      9:
        command: 'reward-9'
        actions:
          - 'coins add {player} 900'
          - 'eco give {player} 75000'
          - 'ecase give suffix_ng {player} 1'
          - 'ecase give suffix_rick {player} 1'
        direct-message: '&6&lХАЛЯВА: &fВы успешно получили &f&l➲ &6&lНАГРАДУ #9'
        broadcast: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fИгрок &6&l{player} &fуспешно получил &4&l⇩
          &8 &8║ &fФранки &f&l➲ &6&l900
          &8 &8║ &fМонеты &f&l➲ &6&l75000
          &8 &8║ &fКейс с титулами рик и морти &f&l➲ &6&l1 штука
          &8 &8║ &fКейс с новогодними титулами &f&l➲ &6&l1 штука
          &8 &8╚ &fЕсли хотите также, выполните команду &f&l➲ &6&l&n/ＦＲＥＥ&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
        not-ready: '&6&lХАЛЯВА: &fВам необходимо отыграть еще &f&l➲ &6&l{remains}'
        already-given: '&6&lХАЛЯВА: &fВы уже получали данную награду.'
        delay: 240m
        notification: |
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r
          &8 &8╔ &fВы можете получить &4&l⇩
          &8 &8║ &fФранки &f&l➲ &6&l900
          &8 &8║ &fМонеты &f&l➲ &6&l75000
          &8 &8║ &fКейс с титулами рик и морти &f&l➲ &6&l1 штука
          &8 &8║ &fКейс с новогодними титулами &f&l➲ &6&l1 штука
          &8 &8╚ &fДля получения награды за наигранное время, выполните команду &f&l➲ &6&l&n/reward-9&6
          &r &r
          §c▄§6▀§e▄§a▀§b▄§9▀§d▄§c▀§6▄§e▀§a▄§b▀§9▄§d▀§c▄§6▀§e▄§a▀§b▄§9▀§d▄
          &r &r

reset-complete:
  chat: '&6&lХАЛЯВА: &fТаймер сброшен. &fВы можете заново получить награды, для этого выполните команду &f&l➲ &6&l&n/ＦＲＥＥ&6'
  title: "&c&l⚠ &6&lТАЙМЕР СБРОШЕН &c&l⚠"

depends: '&6&lХАЛЯВА: &fЧтобы получить данную награду, вам необходимо получить предыдущую награду.'
chain-already-given: '&6&lХАЛЯВА: &fВы уже получали данную награду.'