# Лимит на подключение с одинаковых адресов
limit: 2

# Сообщение о кике
disconnectMessage: "&f&lВЫ ПРЕВЫСИЛИ ЛИМИТ, ОДНОВРЕМЕННО ЗАПУЩЕННЫХ АККАУНТОВ С ОДНОГО АЙПИ! ДАННЫЙ ЛИМИТ СОСТАВЛЯЕТ &6&l{limit} &f&lАККАУНТА"
