# Максимум взрывных и туманных зелий в одном стаке (1-99)
splash_potions_stack: 32

# Максимум обычных питьевых зелий в одном стаке (1-99)
potions_stack: 64

# Радиус объединения одинаковых выброшенных зелий
near_stack_potions: 3

# Разрешить стаки и обычное перетаскивание зелий через ЛКМ/ПКМ
inventory_stack: true
