furnaces:
  # Печки (Можно добавить печек сколько угодно (кастомно))
  doubleFurnace:
    name: '&a&lУДАЧЛИВАЯ ПЕЧКА'
    lore:
      - ''
      - '&e■ &fПечка удачливая'
      - ''
      - '&c✚ &fПлавит в 2 раза больше'
      - ''
    result: 2 # В 2 раза больше ресуров будет приносить печка
    enchant: true # Сделать чтобы печка зачарована в руке (тип зачарования будет скрыт)
  speedFurnace:
    name: '&a&lЭФФЕКТИВНАЯ ПЕЧКА'
    lore:
      - ''
      - '&e■ &fПечка эффективная'
      - ''
      - '&c✚ &fПлавит в 2 раза быстрей'
      - ''
    cooktime: 2 # В 2 раза быстрее будет плавить печка
    enchant: true # Сделать чтобы печка зачарована в руке (тип зачарования будет скрыт)
  smeltFurnace:
    name: '&a&lТОПЛИВНАЯ ПЕЧКА'
    lore:
      - ''
      - '&e■ &fПечка топливная'
      - ''
      - '&c✚ &fТратит в 2 раза меньше топлива'
      - ''
    burntime: 2 # В 2 раза дольше будет плавиться топливо
    enchant: true # Сделать чтобы печка зачарована в руке (тип зачарования будет скрыт)
  superFurnace:
    name: '&a&lСУПЕР ПЕЧКА'
    lore:
      - ''
      - '&e■ &fСупер печка'
      - ''
      - '&c✚ &fПлавит в 2 раза больше'
      - '&c✚ &fПлавит в 2 раза быстрей'
      - '&c✚ &fТратит в 2 раза меньше топлива'
      - ''
    burntime: 2 # В 2 раза дольше будет плавиться топливо
    result: 2 # В 2 раза больше ресуров будет приносить печка
    cooktime: 2 # В 2 раза быстрее будет плавить печка
    enchant: true # Сделать чтобы печка зачарована в руке (тип зачарования будет скрыт)
messages:
  prefix: '&6&lFURNACE &8▪ '
  no-permission: 'У Вас недостаточно прав!'
  command-notfound: 'Неизвестная команда!'
  give:
    usage: '&6/efurnace give &f[&eИгрок&f] &f[&eПечь&f] &f- Выдать игроку печку!'
    player-null: 'Игрок не найден!'
    furnace-null: 'Печка не найдена!'
    complete: 'Печка успешно выдана!'
  list:
    usage: '&6/efurnace list &f- Список печек!'
    title: 'Список печек:'
    format: '&e%step% &f- &e%name%'